version: "3"

rpc:
  listen: "tcp://127.0.0.1:6001"

server:
  command: "php src/worker.php"

http:
  address: "0.0.0.0:80"
  middleware:
    - "static"
  static:
    dir: "public"
    allow:
      - ".html"
      - ".txt"
      - ".css"
      - ".js"
      - ".ico"
  pool:
    num_workers: 2
    max_jobs: 64
