version: "3"

rpc:
  listen: "tcp://127.0.0.1:6001"

server:
  command: "php public/index.php"
  env:
    APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: "0.0.0.0:80"
  middleware:
    - "static"
  static:
    dir: "public"
    allow:
      - ".html"
      - ".txt"
      - ".css"
      - ".js"
      - ".ico"
      - ".svg"
      - ".woff"
      - ".woff2"
      - ".png"
      - ".jpg"
      - ".gif"
      - ".json"
  pool:
    num_workers: 4
    max_jobs: 64
    supervisor:
      max_worker_memory: 128

logs:
  mode: production
  level: info
  encoding: json
  output: stderr

metrics:
  address: "0.0.0.0:2112"
